#!/usr/bin/env bash
# This script displays the PID and process name of processes containing the word "bash"

for pid_dir in /proc/[0-9]*; do
    pid=$(basename "$pid_dir")

    if [[ -f "$pid_dir/cmdline" && $(<"$pid_dir/cmdline") =~ bash ]]; then
        process_name=$(tr '\0' ' ' < "$pid_dir/cmdline")

        echo "PID: $pid, Process Name: $process_name"
    fi
done
