#!/usr/bin/env bash
# Find the PID of the process

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$pid" ]; then
    kill "$pid"
    echo "Process $pid stopped successfully"
else
    echo "Process not found or already stopped"
fi
