#!/usr/bin/env bash
# This script generates a story based on the content of the /etc/passwd file


while IFS=: read -r username password uid gid info homedir shell; do
    user_info=$(grep "^$username:" /etc/passwd | cut -d: -f5)
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell."
    echo "User ID's place is protected by the passcode $password, more info about the user here: $uid $user_info"
    echo "-------------------------------------------------------"
done < /etc/passwd
