#!/usr/bin/env bash
# This script displays "Best School" 10 times, and on the 9th iteration, it displays "Best School" and then "Hi" on a new line

counter=1

check_counter() {
    if [ $counter -eq 10 ]; then
        return 0
    else
        return 1
    fi
}

while [ $counter -le 10 ]; do
    if check_counter; then
        echo "Hi"
    fi
    echo "Best School"
    ((counter++))
done
