#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and performs specific actions for certain iterations

# Initialize counter
counter=1

# Loop while counter is less than or equal to 20
while [ $counter -le 20 ]; do
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac
    # Increment counter
    ((counter++))
done
