#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
        [ $(($hour * 60 + $minute)) -eq 70 ] && break 2
    done
    ((hour++))
    minute=0
done | head -n 70
