#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -le 13 ]; do
    if [ $hour -eq 0 ]; then
        echo "Hour: $hour"
        ((hour++))
    elif [[ $minute -eq 60 ]]; then
        echo "Hour: $hour"
        ((hour++))
        minute=1
    fi
    if [[ $minute -eq 59 && $hour -eq 13 ]]; then
        echo "59"
        break
    fi
    
    echo $minute
    ((minute++))

    
done
