#!/usr/bin/env bash
# Create a temporary file and add the custom hosts entries
# Replace the /etc/hosts file with the temporary file
# Restart networking services to apply changes
# Verify that localhost and facebook.com are resolving to the correct IP addresses

echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
sudo systemctl restart networking
ping -c 1 localhost
ping -c 1 facebook.com
